# Generated by Django 3.2.9 on 2021-11-12 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=1000)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='movie/posters')),
                ('cast', models.ManyToManyField(to='todo.Cast')),
                ('categories', models.ManyToManyField(to='todo.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=1000)),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='movie/posters')),
                ('cast', models.ManyToManyField(to='todo.Cast')),
                ('categories', models.ManyToManyField(to='todo.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
