# Generated by Django 3.2.9 on 2021-11-18 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiels', '0003_alter_userprofile_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='name',
            new_name='username',
        ),
    ]
